services:
  # API сервис
  - type: web
    name: url-cutter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DATABASE_URL
        fromDatabase:
          name: url_cutter_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: BASE_URL
        value: https://url-cutter-tayar.onrender.com
    autoDeploy: true
    plan: free

  # Valkey (Redis) сервис
  - type: redis
    name: url_cutter_valkey
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic
    plan: free

databases:
  # База данных PostgreSQL
  - name: url_cutter_db
    databaseName: url_cutter
    user: url_cutter 
    plan: free