services:
  - type: web
    name: url-cutter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DATABASE_URL
        fromDatabase:
          name: url_cutter_db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: url_cutter_redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://url-cutter-tayar902.onrender.com
      - key: LINK_EXPIRATION_DAYS
        value: 180
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PROJECT_NAME
        value: URL Cutter
      - key: VERSION
        value: 1.0.0
      - key: API_V1_STR
        value: /api/v1
    plan: free

databases:
  # База данных PostgreSQL
  - name: url_cutter_db
    databaseName: url_cutter
    user: url_cutter
    plan: free

  - name: url_cutter_redis
    databaseName: url_cutter_redis
    plan: free 