services:
  # API сервис
  - type: web
    name: url-cutter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url-cutter-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: url-cutter-valkey
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: BASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

  # Valkey (Redis) сервис
  - type: redis
    name: url-cutter-valkey
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic
    plan: free

databases:
  # База данных PostgreSQL
  - name: url-cutter-db
    databaseName: url_cutter
    user: url_cutter 